apiVersion: v1
kind: ReplicationController
metadata:
  name: cncfdemo
spec:
  replicas: 1
  selector:
    app: bbc
  template:
    metadata:
      labels:
        app: bbc
    spec:
      containers:
      - name: cncfdemo
        image: devnode:5000/mynode
        imagePullPolicy: Always
        ports:
          - name: cncfdemoport
            containerPort: 80
